[workspace]
name = "xsf"
version = "0.2.2"
description = "Special function implementations."
authors = [
  "Albert Steppi <albert.steppi@gmail.com>",
  "Irwin Zaid <irwin.zaid@gmail.com>",
  "Florian Bourgey <bourgeyflorian@gmail.com>",
  "Lucas Colley <lucas.colley8@gmail.com>",
  "Daniel Schmitz <danielschmitzsiegen@googlemail.com>",
]
platforms = [
  "linux-64",
  "linux-aarch64",
  "osx-arm64",
  "win-64",
  "osx-64",
]
channels = ["https://prefix.dev/conda-forge"]
requires-pixi = ">=0.74.0"
preview = ["pixi-build"]

[workspace.target.win.build-variants]
cxx_compiler = ["vs2026"]

# this currently hits https://github.com/prefix-dev/pixi/issues/6727,
# uncomment when that is resolved
# [package]
# name = { workspace = true }
# version = { workspace = true }
# build.backend.name = "pixi-build-cmake"

[target.unix.activation]
env.SHARE_PREFIX = "$CONDA_PREFIX/share"

[target.win.activation]
env.SHARE_PREFIX = "%CONDA_PREFIX%/Library/share"

[tasks.tests]
description = "Run test suite."
args = [{ arg = "parallel", default = "2" }]
cmd = ["ctest", "--output-on-failure", "--test-dir", "$SHARE_PREFIX/xsf/tests", "-j{{ parallel }}"]
default-environment = "tests-release"

[environments]
tests-release = {
  solve-group = "xsf-release",
  dependencies.xsf.path = "packages/tests-release",
}
tests-debug = {
  dependencies.xsf.path = "packages/tests-debug",
}

coverage = {
  platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64"],
  dependencies = {
    xsf.path = "packages/coverage",
  },
  activation = {
    env = {
      COVERAGE_DIR = "$CONDA_PREFIX/share/xsf/cov",
      GCOV_PREFIX = "$CONDA_PREFIX/share/xsf/cov",
    },
    scripts = ["scripts/coverage_activation.sh"],
  },
  tasks = {
    coverage = {
      description = "Generate HTML coverage report.",
      depends-on = [{
        task = "tests",
        environment = "coverage",
      }],
      cmd = "scripts/coverage.sh",
    },
    open-coverage = {
      description = "Open HTML coverage report.",
      depends-on = "coverage",
      cmd = ["open", "$SHARE_PREFIX/xsf/cov/coverage_report/index.html"],
    },
  }
}

cupy-tests = {
  solve-group = "xsf-release",
  platforms = ["linux-64"],
  dependencies = {
    cupy = "*",
    pytest-forked = "*",
    polars = "*",
  },
  tasks.test-cupy = {
    description = "Run CuPy integration tests.",
    cmd = "pytest --forked python_tests/test_cupy.py",
  },
}

lint = {
  dependencies = {
    git = "*",
    clang-format = "*",
  },
  tasks = {
    format = {
      description = "Format tracked C++ source and header files in place.",
      cmd = "git ls-files '*.cpp' '*.h' | xargs clang-format --style=file -i",
    },
    format-dry-error = {
      description = "Check C++ formatting and fail if any file needs changes.",
      cmd = "git ls-files '*.cpp' '*.h' | xargs clang-format --style=file --Werror --dry-run",
    },
  },
}
