[package]
name = { workspace = true }
version = { workspace = true }
build = {
  backend.name = "pixi-build-cmake",
  config.extra-args = ["-DBUILD_TESTS=ON"],
  flags = ["tests", "release"],
  source.path = "../..",
}
build-dependencies = {
  xsref = {
    git = "https://github.com/lucascolley/xsref",
    rev = "6d4891c435c8525d535bf5038142414603edbd27",
  },
}
host-dependencies = {
  catch2 = "*",
  libarrow-all = "*",
}
run-dependencies = {
  cmake = "*",
}
