name: GPU jobs

on: [ push, pull_request ]

permissions:
   contents: read  # to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cupy_tests:
    name: CuPy GPU
    runs-on: "cirun-scipy-onprem-gpu--${{ github.run_id }}"
    steps:
      - name: Checkout xsf repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive

      - name: Define default CuPy cache path
        run: |
          # We don't want to change the directory, and $HOME isn't available for `env:`
          echo "CUPY_CACHE_DIR=$HOME/.cupy/kernel_cache" >> $GITHUB_ENV

      - name: Cache CuPy kernels
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ env.CUPY_CACHE_DIR }}
          key: cupy-v0-${{ github.run_id }}
          restore-keys: cupy-v0

      - name: run nvidia-smi
        run: nvidia-smi

      - name: run nvidia-smi --query
        run: nvidia-smi --query

      - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          pixi-version: v0.77.0
          manifest-path: pixi.toml
          cache: true
          cache-key: gpu-pixi-
          environments: cupy-tests

      - name: Run CuPy tests
        run: pixi run test-cupy
