name: Tests

on: [ push, pull_request ]

permissions:
  contents: read  # to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  coverage:
    name: Release + Coverage ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, ubuntu-24.04-arm, macos-latest]
        environment: [coverage]
    env:
      CCACHE_DIR: ${{ github.workspace }}/packages/coverage/.ccache
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/ccache
        with:
          key_segment: ${{ github.workflow }}-${{ matrix.environment }}-${{ matrix.runs-on }}
      - name: Setup ${{ matrix.environment }} environment
        uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          pixi-version: v0.77.0
          cache: true
          cache-key: pixi-v0-${{ github.job }}
          environments: ${{ matrix.environment }}
      - name: Ccache performance
        shell: bash
        run: pixi exec ccache -s
      - name: Determine number of workers
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            echo "NUM_WORKERS=$(nproc)" >> $GITHUB_ENV
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            echo "NUM_WORKERS=$(sysctl -n hw.ncpu)" >> $GITHUB_ENV
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "NUM_WORKERS=$NUMBER_OF_PROCESSORS" >> "$GITHUB_ENV"
          fi
        shell: bash
      - name: Run tests
        run: pixi run --environment=coverage tests $NUM_WORKERS
      - name: Generate coverage report
        run: pixi run --skip-deps coverage
      - name: Upload HTML coverage report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: cov-html-${{ matrix.runs-on }}
          path: .pixi/envs/coverage/share/xsf/cov/coverage_report/**

  tests-release:
    # for platforms without coverage support
    name: Release
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [windows-latest]
        environment: [tests-release]
    env:
      CCACHE_DIR: ${{ github.workspace }}/packages/tests-release/.ccache
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/ccache
        with:
          key_segment: ${{ github.workflow }}-${{ matrix.environment }}-${{ matrix.runs-on }}
      - name: Setup ${{ matrix.environment }} environment
        uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          pixi-version: v0.77.0
          cache: true
          cache-key: pixi-v0-${{ github.job }}
          environments: ${{ matrix.environment }}
      - name: Ccache performance
        shell: bash
        run: pixi exec ccache -s
      - name: Determine number of workers
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            echo "NUM_WORKERS=$(nproc)" >> $GITHUB_ENV
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            echo "NUM_WORKERS=$(sysctl -n hw.ncpu)" >> $GITHUB_ENV
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "NUM_WORKERS=$NUMBER_OF_PROCESSORS" >> "$GITHUB_ENV"
          fi
        shell: bash
      - name: Run tests
        run: pixi run --environment=${{ matrix.environment }} tests $NUM_WORKERS

  tests-debug:
    name: Debug ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, ubuntu-24.04-arm]
        environment: [tests-debug]
    env:
      CCACHE_DIR: ${{ github.workspace }}/packages/tests-debug/.ccache
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/ccache
        with:
          key_segment: ${{ github.workflow }}-${{ matrix.environment }}-${{ matrix.runs-on }}
      - name: Setup ${{ matrix.environment }} environment
        uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          pixi-version: v0.77.0
          cache: true
          cache-key: pixi-v0-${{ github.job }}
          environments: ${{ matrix.environment }}
      - name: Ccache performance
        shell: bash
        run: pixi exec ccache -s
      - name: Determine number of workers
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            echo "NUM_WORKERS=$(nproc)" >> $GITHUB_ENV
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            echo "NUM_WORKERS=$(sysctl -n hw.ncpu)" >> $GITHUB_ENV
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "NUM_WORKERS=$NUMBER_OF_PROCESSORS" >> "$GITHUB_ENV"
          fi
        shell: bash
      - name: Run tests
        run: pixi run --environment=${{ matrix.environment }} tests $NUM_WORKERS
