name: Tests

on: [ push, pull_request ]

permissions:
  contents: read  # to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  coverage:
    name: Release + Coverage ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, ubuntu-24.04-arm, macos-latest]
        environment: [coverage]
    steps:
      - name: Checkout xsf
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup test environment
        uses: ./.github/setup-test-env
        with:
          environment: ${{ matrix.environment }}
      - name: Determine number of workers
        uses: ./.github/num-workers
      - name: Run tests
        run: pixi run --environment=${{ matrix.environment }} tests $NUM_WORKERS
      - name: Generate coverage report
        run: pixi run --skip-deps coverage
      - name: Upload HTML coverage report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: cov-html-${{ matrix.runs-on }}
          path: .pixi/envs/coverage/share/xsf/cov/coverage_report/**

  tests-release:
    # for platforms without coverage support
    name: Release
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [windows-latest]
        environment: [tests-release]
    steps:
      - name: Checkout xsf
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup test environment
        uses: ./.github/setup-test-env
        with:
          environment: ${{ matrix.environment }}
      - name: Determine number of workers
        uses: ./.github/num-workers
      - name: Run tests
        run: pixi run --environment=${{ matrix.environment }} tests $NUM_WORKERS

  tests-debug:
    name: Debug ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, ubuntu-24.04-arm]
        environment: [tests-debug]
    steps:
      - name: Checkout xsf
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup test environment
        uses: ./.github/setup-test-env
        with:
          environment: ${{ matrix.environment }}
      - name: Determine number of workers
        uses: ./.github/num-workers
      - name: Run tests
        run: pixi run --environment=${{ matrix.environment }} tests $NUM_WORKERS
